# Generated by Django 2.2 on 2020-07-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorecultureapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalPhotography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('imgposter', models.CharField(max_length=120)),
                ('culturalphotographyimg', models.ImageField(max_length=255, upload_to='img/')),
            ],
        ),
    ]
